unit HELP;

interface

const

  hcBenchmarks           = 108;
  hcConfig               = 114;
  hcConfigBench          = 115;
  hcConfigGlobal         = 117;
  hcConfigRPM            = 116;
  hcDisk                 = 104;
  hcDiskSelect           = 105;
  hcDiskSelectList       = 106;
  hcDiskSelectManual     = 107;
  hcFile                 = 100;
  hcFileDOSShell         = 102;
  hcFileExit             = 103;
  hcFileSave             = 101;
  hcGraphs               = 109;
  hcGraphsCache          = 113;
  hcGraphsRead           = 110;
  hcGraphsVerify         = 112;
  hcGraphsWrite          = 111;
  hcMainIndex            = 7;
  hcMsgBoxExit           = 500;
  hcMsgBoxMultitask      = 501;
  hcNoContext            = 0;

implementation

end.
